INFO 2025-04-29 17:49:53,028 autoreload Watching for file changes with StatReloader
ERROR 2025-04-29 17:50:26,599 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 749, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 58, in as_crispy_form
    template = uni_form_template(template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 21, in uni_form_template
    return get_template("%s/uni_form.html" % template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
WARNING 2025-04-29 17:50:26,875 log Not Found: /favicon.ico
ERROR 2025-04-29 17:51:27,857 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 749, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 58, in as_crispy_form
    template = uni_form_template(template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 21, in uni_form_template
    return get_template("%s/uni_form.html" % template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
ERROR 2025-04-29 17:51:40,867 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 749, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 58, in as_crispy_form
    template = uni_form_template(template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 21, in uni_form_template
    return get_template("%s/uni_form.html" % template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
ERROR 2025-04-29 17:51:45,880 log Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 1075, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\base.py", line 749, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 58, in as_crispy_form
    template = uni_form_template(template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\crispy_forms\templatetags\crispy_forms_filters.py", line 21, in uni_form_template
    return get_template("%s/uni_form.html" % template_pack)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snhaidary\Downloads\IT Tracking System\venv\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bootstrap4/uni_form.html
INFO 2025-04-29 17:56:14,747 autoreload Watching for file changes with StatReloader
WARNING 2025-04-29 17:56:47,914 log Not Found: /l
INFO 2025-04-30 10:31:55,565 autoreload Watching for file changes with StatReloader
WARNING 2025-04-30 10:32:16,590 log Not Found: /favicon.ico
INFO 2025-04-30 10:50:01,421 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 11:51:33,291 autoreload Watching for file changes with StatReloader
WARNING 2025-04-30 11:51:44,646 base Method Not Allowed (GET): /logout/
WARNING 2025-04-30 11:51:44,647 log Method Not Allowed: /logout/
WARNING 2025-04-30 11:51:56,042 base Method Not Allowed (GET): /logout/
WARNING 2025-04-30 11:51:56,043 log Method Not Allowed: /logout/
INFO 2025-04-30 12:24:13,644 autoreload Watching for file changes with StatReloader
WARNING 2025-04-30 12:25:09,110 base Method Not Allowed (GET): /logout/
WARNING 2025-04-30 12:25:09,111 log Method Not Allowed: /logout/
WARNING 2025-04-30 12:25:49,260 base Method Not Allowed (GET): /logout/
WARNING 2025-04-30 12:25:49,261 log Method Not Allowed: /logout/
INFO 2025-04-30 12:38:59,344 views Asset created: BDAsset001 by snhaidary
INFO 2025-04-30 15:52:50,737 autoreload Watching for file changes with StatReloader
INFO 2025-04-30 15:53:26,083 views Asset updated: BDAsset-001 by snhaidary
INFO 2025-04-30 15:53:57,433 views Asset updated: BDAsset001 by snhaidary
INFO 2025-04-30 15:55:51,808 views Asset created: BDAsset-002 by snhaidary
WARNING 2025-04-30 16:00:10,070 log Not Found: /favicon.ico
INFO 2025-04-30 16:00:36,737 views Asset updated: BDAsset-002 by snhaidary
INFO 2025-04-30 19:02:17,239 autoreload Watching for file changes with StatReloader
WARNING 2025-04-30 19:02:33,227 log Not Found: /favicon.ico
INFO 2025-04-30 19:18:32,064 views Asset updated: BDAsset-002 by dentry
INFO 2025-04-30 19:19:41,149 views Asset created: BDAsset-003 by dentry
INFO 2025-04-30 19:20:13,542 views Asset updated: BDAsset-002 by dentry
INFO 2025-05-04 11:34:43,815 autoreload Watching for file changes with StatReloader
WARNING 2025-05-04 11:35:04,885 log Not Found: /favicon.ico
INFO 2025-05-04 11:46:40,373 views Asset created: BDAsset-004 by snhaidary
